GET https://localhost:3000/posts
authorisation: bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjA4Njk2NjF9.YSScVW0xoHXjKKKiqLx2C6ojtGV9HVrOj4Tbf6IsKJw

###
POST https://localhost:4000/login
Content-Type: application/json

{
    "username":"amol"
}